apiVersion: batch.freecross.com/v1
kind: WebsiteDeployment
metadata:
  name: websitedeployment-sample
spec:
  # TODO(user): Add fields here
  deploymentTemplate:
    metadata:
      labels:
        app: default-provider
      spec:
        replicas: 1
        template:
          metadata:
            name: "[NAME]"
            labels:
              webserver: "[NAME]"
          spec:
            containers:
              - image: nginx:alpine
                name: main
                volumeMounts:
                  - name: html
                    mountPath: "/usr/share/nginx/html"
                    readOnly: true
                ports:
                  - containerPort: 80
                    protocol: TCP
              - image: openweb/git-sync
                name: git-sync
                env:
                  - name: GIT_SYNC_REPO
                    value: "[GIT-REPO]"
                  - name: GIT_SYNC_DEST
                    value: "/gitrepo"
                  - name: GIT_SYNC_BRANCH
                    value: master
                  - name: GIT_SYNC_REV
                    value: FETCH_HEAD
                  - name: GIT_SYNC_WAIT
                    value: '10'
                volumeMounts:
                  - name: html
                    mountPath: "/gitrepo"
            volumes:
              - name: html
                emptyDir:
                  medium: ''
  serviceTemplate:
    metadata:
      labels:
        app: default-provider
      spec:
        type: NodePort
        ports:
          - port: 80
            protocol: TCP
            targetPort: 80
        selector:
          webserver: "[NAME]"
